### ISSUE TITLE
Only decode header

### ISSUE THREAD

**Issue by Farkal** [hidekatsu-izuno/josekit-rs#1]
I would like to decode the header of a JWT to get the kid (i need the kid to get the JWK from redis). 
Currently there is no way to get it because `decode_unsecured` don't want to parse JWT with signature part or alg header.
The best would be to create a trait for `JwkSet` and allow to customize how the `JwkSet` handle when and id is missing.

And thx for this lib, it's the only one able to manage JWK for ECDSA algorythms all other libs depend on `ring` which is only able to decode it from PEM or DER (and i didn't find a way to generate PEM from JWK).

**Comment by hidekatsu-izuno** [comment]
I released v0.4.0. In this version I added a jwt::decode_header(input) function.
I hope this feature is usefull to you.

**Comment by Farkal** [comment]
Thank you very much !
