### ISSUE TITLE
Decoding/Verifying with JWK Set or Verifier Selector

### ISSUE THREAD

**Issue by naftulikay** [hidekatsu-izuno/josekit-rs#13]
## Background

I have [written an example](https://github.com/naftulikay/rocket-oauth-jwt-demo/blob/b23dae9e565ad80c2d66e1e98a065486238a3fea/src/examples/gen-key.rs) using `josekit` to just demonstrate the following:

 1. Generate public/private EdDSA/Curve25519 keypair.
 2. DIsplay them in PEM/JWK format.
 3. Generate header/claims.
 4. Generate signed token from header/claims using the private key.
 5. Verify that signed token using the public key.

I'm currently using [`josekit::jwt::decode_with_verifier`](https://docs.rs/josekit/0.7.4/josekit/jwt/fn.decode_with_verifier.html) to verify the signed token, but I'd like to use either [`josekit::jwt::decode_with_verifier_in_jwk_set`](https://docs.rs/josekit/0.7.4/josekit/jwt/fn.decode_with_verifier_in_jwk_set.html) or [`josekit::jwt::decode_with_verifier_selector`](https://docs.rs/josekit/0.7.4/josekit/jwt/fn.decode_with_verifier_selector.html) so that I can verify with a list of different potential keys.

## Goal

The exact use-case that I'm trying to support is similar to the way that Google provides their JWT signing keys (in PEM format [here](https://www.googleapis.com/oauth2/v1/certs), in JWK format [here](https://www.googleapis.com/oauth2/v3/certs)) for use during OAuth 2 flows for serverside applications:

 1. On start, your application fetches the Google JWT signing keys from either:
    - PEM: https://www.googleapis.com/oauth2/v1/certs
    - JWK: https://www.googleapis.com/oauth2/v3/certs
 2. When Google's OAuth flow sends a `application/x-www-form-urlencoded` POST request including a JWT token, your application is responsible for verifying the returned token using their certificate list from above.

So far, I've been using the [`jwt`](https://docs.rs/jwt/0.16.0/jwt/index.html) crate, but `josekit` supports much more, so I'm trying to migrate my application. 

## Question

I'll only be signing tokens with one key at a time, but I'd like to be verifying tokens with a list of public keys. I'm a bit confused by the APIs for `decode_with_verifier_in_jwk_set`, where the API looks like this:

```rust
pub fn decode_with_verifier_selector<'a, F>(
    input: impl AsRef<[u8]>,
    selector: F,
) -> Result<(JwtPayload, JwsHeader), JoseError>
where
    F: Fn(&JwsHeader) -> Result<Option<&'a dyn JwsVerifier>, JoseError>
```

as well as `decode_with_verifier_selector`, where the API looks like this:

```rust
pub fn decode_with_verifier_in_jwk_set<F>(
    input: impl AsRef<[u8]>,
    jwk_set: &JwkSet,
    selector: F,
) -> Result<(JwtPayload, JwsHeader), JoseError>
where
    F: Fn(&Jwk) -> Result<Option<&dyn JwsVerifier>, JoseError>
```

I can't seem to determine what the expected usage of these APIs are. I'm probably going to have a [`josekit::jwk::JwkSet`](https://docs.rs/josekit/0.7.4/josekit/jwk/struct.JwkSet.html) of public keys, and I'd like to use the `kid` field in the JWT header to select the JWK key based on its key id.

How do I use these APIs to do this?

**Comment by naftulikay** [comment]
I was able to solve the issue, full source code [available here](https://gist.github.com/naftulikay/82af626388e592e4ba1072f7796098a5).

In short:

```rust
use josekit::jwk::alg::ed::{EdCurve, EdKeyPair};
use josekit::jwk::{Jwk, KeyPair};
use josekit::jws::alg::eddsa::{EddsaJwsSigner, EdssaJwsVerifier};
use josekit::jws::{EdDSA, JwsHeader};
use josekit::jwt::{self, JwtPayload};

// generate the keypair and its jwk representations
let keypair: EdKeyPair = EdDSA.generate_key_pair(EdCurve::Ed25519).unwrap();
let jwk_keypair: Jwk = keypair.to_jwk_key_pair();
let jwk_public: Jwk = jwk_keypair.to_public_key().unwrap();

// create a token signer using the private key
let token_signer: EddsaJwsSigner = EdDSA.signer_from_jwk(&jwk_keypair).unwrap();

// generate header and claims to sign
let (header, claims): (JwsHeader, JwtPayload) = create_token();

// sign with the private key
let token: String = jwt::encode_with_signer(&claims, &header, &token_signer).unwrap();

// create a verifier
let token_verifier: EddsaJwsVerifier = EdDSA.verifier_from_jwk(&jwk_public).unwrap();

// verify the claims using a selector that chooses a key based on the header's key id
let (_verified_claims, _verified_header) =
    jwt::decode_with_verifier_selector(token, |header| {
        if let Some(header_key_id) = header.key_id() {
            // if the header's key id matches our key's key id, use that as the verifier
            if header_key_id == jwk_pub.key_id().unwrap() {
                return Ok(Some(&token_verifier));
            }
        }

        Ok(None)
    })
    .unwrap_or_else(|e| {
        eprintln!("Failed to decode/verify token: {}", e);
        exit(1)
    });
```

**Comment by hidekatsu-izuno** [comment]
I'm glad you were able to solve the problem. I'm sorry I am too busy to answer your issue.

**Comment by w0rm** [comment]
Hi @naftulikay! In your original message you mentioned that you were going to use jwk_set of public keys, however the solution you provided was for a single jwk, and you created the `token_verifier` outside of the `selector` closure and referenced it. I am fairly new to rust, and I cannot figure out how to implement something like this that dynamically selects a verifier based on jwk:

```
let (_verified_claims, _verified_header) =
       jwt::decode_with_verifier_in_jwk_set(token, &jwk_set, |jwk| match jwk.algorithm() {
            Some("RS256") => Ok(Some(&RS256.verifier_from_jwk(jwk)?)),
            Some("P-521") => Ok(Some(&ES512.verifier_from_jwk(jwk)?)),
            _ => Ok(None),
        })?;
```

This doesn't work because of `cannot return value referencing temporary value returns a value referencing data owned by the current function`. 

@hidekatsu-izuno I tried to search the documentation and the tests and couldn't find a usage example for any of the functions that take the selector `Fn`.

**Comment by Wicpar** [comment]
I'm also looking for a way to universally verify a JWT with any key in the keyset no matter the algorithm.
For now i'll make do with brute forcing all algorithms.

**Comment by w0rm** [comment]
@Wicpar I've ended up loading a mapping from key id to a verifier:

```rust
let jws_verifiers = JwkSet::from_bytes(bytes)?
            .keys()
            .into_iter()
            .filter_map(|jwk| {
                let kid = jwk.key_id()?.to_string();
                if jwk.key_use() != Some("sig") {
                    return None;
                }
                match jwk.key_type() {
                    "RSA" => Some(RS256.verifier_from_jwk(jwk).map(|v| (kid, v.box_clone()))),
                    "EC" => Some(ES512.verifier_from_jwk(jwk).map(|v| (kid, v.box_clone()))),
                    "OKP" => Some(EdDSA.verifier_from_jwk(jwk).map(|v| (kid, v.box_clone()))),
                    _ => None,
                }
            })
            .collect::<Result<BTreeMap<String, Box<dyn JwsVerifier>>, _>>()?;
```


And then later I get a verifier by the key id and use it to validate a token:

```rust
        let (payload, _header) = decode_with_verifier_selector(&token, |header| {
            Ok(header
                .key_id()
                .and_then(|kid| jws_verifiers.get(kid))
                .map(|el| el.as_ref()))
        })?;
```

**Comment by Wicpar** [comment]
Thanks @w0rm , but i found https://github.com/lawliet89/biscuit which is a lot easier to use.
Also i cannot rely on KID, as the jwts are user provided.

**Comment by w0rm** [comment]
@Wicpar I've just remembered why I didn't go with biscuit, it is because I needed `ES512`, that is not supported: https://github.com/lawliet89/biscuit/blob/0333da5a60f626d418d5575324a353c5eae1dc51/src/jwa.rs#L100

**Comment by Wicpar** [comment]
@w0rm i noticed, but that is not a requirement for me yet. I guess i'll refactor it there when it comes to it.
