### ISSUE TITLE
set_x509_certificate_chain (x5c) implementation is wrong

### ISSUE THREAD

**Issue by curtisleefulton** [hidekatsu-izuno/josekit-rs#15]
Issue: set_x509_certificate_chain() encodes input as base64url-encoded, not plain base64-encoded.

Per RFC 7515, 4.1.6 (https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.6) each string entry in the x5c header parameter is a "base64-encoded (Section 4 of [RFC4648] -- not base64url-encoded) DER [ITU.X690.2008] PKIX certificate value."

This is a one-line fix in jws_header.rs

Likewise,  x509_certificate_chain() has the same issue in reverse.

Of course, if you're using josekit for both encoding and decoding, you'll never notice :)

**Comment by curtisleefulton** [comment]
https://github.com/hidekatsu-izuno/josekit-rs/pull/16

**Comment by hidekatsu-izuno** [comment]
I released a verson 0.8.0 fixed this problem.

**Comment by curtisleefulton** [comment]
thank you!
