### ISSUE TITLE
RUSTSEC-2023-0022 to 0024 => security advisory on openssl 

### ISSUE THREAD

**Issue by cemoktra** [hidekatsu-izuno/josekit-rs#23]
https://rustsec.org/advisories/RUSTSEC-2023-0022
https://rustsec.org/advisories/RUSTSEC-2023-0023
https://rustsec.org/advisories/RUSTSEC-2023-0024

Version needs to be bumped

**Comment by hidekatsu-izuno** [comment]
I released v0.8.3. Close. Minimum OpenSSL version changed to 0.10.51.
