### ISSUE TITLE
Allow to enable openssl vendored feature to cross compile

### ISSUE THREAD

**Issue by cavivie** [hidekatsu-izuno/josekit-rs#25]
I have a project that needs to be able to compile to multiple targets on the same machine, but it fails when compiling to a non-local platform target because openssl depends on the local libssl library. In order to complete the compilation to multiple targets on the same host machine for this target, we need to enable the vendored feature of openssl, so that it will compile openssl from source at the right time (openssl-src).

[openssl without vendored feature](https://github.com/hidekatsu-izuno/josekit-rs/blob/master/Cargo.toml#L24C20-L24C20)

**Comment by hidekatsu-izuno** [comment]
More details are needed.

**Comment by cavivie** [comment]
@hidekatsu-izuno Sure, updated the issue details.

**Comment by sathyajithps** [comment]
Any updates on this ?  I'm trying to cross compile josekit-rs to windows, its not working.

**Comment by hidekatsu-izuno** [comment]
I added a vendored feature for suppored the openssl/vendored feature on v0.8.4.

You can try `--feature vendored` option
