### ISSUE TITLE
Security vulnerability disclosure

### ISSUE THREAD

**Issue by mschwager** [hidekatsu-izuno/josekit-rs#29]
Hi there,

I'd like to report a potential security vulnerability in this repository. Using GitHub's private reporting would be easiest:

- [Privately reporting a security vulnerability](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability)
- [Configuring private vulnerability reporting for a repository](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository)

If that doesn't work, would you mind suggesting an alternative?

**Comment by hidekatsu-izuno** [comment]
Your report is welcome. I enabled private vulnerability reporting feature of this project. 
Can you try to report it ?

**Comment by hidekatsu-izuno** [comment]
I fixed this Security vulnerability.

**Comment by alexanderkjall** [comment]
Hi, would it be possible to report this to the rustsec database: https://rustsec.org/ ?

That way users of the library would get automatic notifications (if they have integrated cargo-audit in their CI) and/or automatic pull requests to update (if they are on github and have dependabot enabled).
