### ISSUE TITLE
Wrong iv length in JWE header

### ISSUE THREAD

**Issue by kilork** [hidekatsu-izuno/josekit-rs#32]
Hi, I see a small disruption in implementation, or maybe I am reading something wrong (but seems like it is not only me, but also other libraries who fail to parse JWE token created by josekit).

Currently iv is randomly generated from 32 bytes. But according to RFC it must be 96 bits, or 12 bytes.

Reference:

- https://datatracker.ietf.org/doc/html/rfc7518#section-4.7.1.1

**Comment by hidekatsu-izuno** [comment]
Thank you for your reporting. I have identified it as a bug.
I will release a fixed version.

**Comment by hidekatsu-izuno** [comment]
I have released v0.8.6.

**Comment by kilork** [comment]
Great! Thank you for your library, it is very useful!
