### ISSUE TITLE
[QUESTION] How can I cast JoseHeader to JwsHeader?

### ISSUE THREAD

**Issue by fuch1m** [hidekatsu-izuno/josekit-rs#35]
Hello,

So I use the ```decode_header``` function but I want the more specific ```JwsHeader``` instead of ```Box<dyn JoseHeader>``` to make use of the member functions to call ```algorithm``` or ```x509_certificate_sha1_thumbprint``` functions. How can I do it?

```
let header = josekit::jwt::decode_header(jws)?;
```

**Comment by hidekatsu-izuno** [comment]
I implement Any trait for JoseHeader in v0.10.0. You can downcast now!

```rust
let header = josekit::jwt::decode_header(jws)?;
let jws_header = header.into_any().downcast::<JwsHeader>().unwrap(); // Box<JwsHeader>
```
